services:
  api:
    container_name: dev-golang-cron-manager
    build:
      context: ./infra/containers/development
      dockerfile: Dockerfile
    environment:
      DB_DSN_MYSQL_ELEVA_CONTABO: ${DB_DSN_MYSQL_ELEVA_CONTABO}
      DB_DSN_MYSQL_ELEVA: ${DB_DSN_MYSQL_ELEVA}
      JWT_SECRET: ${JWT_SECRET}
      MAILER_EMAIL: ${MAILER_EMAIL}
      MAILER_PASSWORD: ${MAILER_PASSWORD}
      MAILER_SMTP_HOST: ${MAILER_SMTP_HOST}
      MAILER_SMTP_PORT: ${MAILER_SMTP_PORT}
    ports:
      - "8080:8080"
    volumes:
      - .:/srv
    command: sh -c 'go mod download && air'
